- name: Install PHP and extensions
  dnf:
    name:
      - php
      - php-mysqlnd
      - php-fpm
      - php-xml
      - php-cli
      - php-common
    state: present
    update_cache: yes
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
- name: Set permissions
  file:
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    recurse: yes
